name: toms_se_project
description: A new Flutter project.



publish_to: 'none'



version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"




dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.0
  firebase_messaging: ^11.2.15
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  flutter_local_notifications: ^9.4.1
  rive: ^0.8.4




  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^1.0.0




flutter:



  uses-material-design: true


  assets:
    - assets/

